global:
    scrape_interval: 15s
  
scrape_configs:
    - job_name: 'prometheus'
      scrape_interval: 5s
      static_configs:
        - targets: ['localhost:9090']

    - job_name: redis_exporter
      static_configs:
        - targets: ['redis_exporter:9121']

    - job_name: 'spring'
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets: ['spring:8080']

    - job_name: 'spring-test'
      metrics_path: '/prometheus'
      static_configs:
        - targets: ['spring-test:8080']

    - job_name: 'node_exporter'
      metrics_path: '/metrics'
      static_configs:
        - targets: ['node_exporter:9100']